name: 'GitHub Checks'
description: 'Wrapper around the GitHub Checks API'
author: 'Louis Brunner'
inputs:
  token:
    description: 'your GITHUB_TOKEN'
runs:
  using: 'node12'
  main: 'dist/index.js'
